apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
data:
  POSTGRES_USERNAME: "{{.Values.secret.POSTGRES_USER}}"
  POSTGRES_PASSWORD: "{{.Values.secret.POSTGRES_PASSWORD}}"
  POSTGRES_DB: "{{.Values.secret.POSTGRES_DB}}"
