apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.chat.deployment}}
  labels:
    app: {{.Values.chat.deployment}}
spec:
  replicas: {{.Values.chat.replicas}}
  selector:
    matchLabels:
      app: {{.Values.chat.deployment}}
  template:
    metadata:
      labels:
        app: {{.Values.chat.deployment}}
    spec:
      containers:
        - name: {{.Values.chat.deployment}}
          image: awadhootk/rag-service:chat
          ports:
            - containerPort: {{.Values.chat.containerPort}}
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: chat-secret
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chat-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: chat-secret
                  key: POSTGRES_DB
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: chat-secret
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chat-secret
                  key: RABBITMQ_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: REDIS_PORT
            - name: INDEXING_HOST
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: INDEXING_HOST
            - name: INDEXING_PORT
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: INDEXING_PORT
            - name: RAG_HOST
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: RAG_HOST
            - name: RAG_PORT
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: RAG_PORT
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: RABBITMQ_PORT
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: POSTGRES_PORT

---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.chat.service}}
spec:
  selector:
    app: {{.Values.chat.deployment}}
  ports:
    - protocol: TCP
      port: {{.Values.chat.servicePort}}
      targetPort: {{.Values.chat.containerPort}}
