apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Values.postgres.pv.name}}
spec:
  capacity:
    storage: {{.Values.postgres.pv.capacity}}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  local:
    path: {{.Values.postgres.pv.path}}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node1
