apiVersion: v1
kind: Secret
metadata:
  name: rag-secret
type: Opaque
data:
  GOOGLE_API_KEY: {{.Values.secret.GOOGLE_API_KEY}}
  RABBITMQ_USERNAME: {{.Values.secret.RABBITMQ_DEFAULT_USER}}
  RABBITMQ_PASSWORD: {{.Values.secret.RABBITMQ_DEFAULT_PASS}}
