apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Values.redis.deployment}}
spec:
  selector:
    matchLabels:
      app: {{.Values.redis.deployment}}
  serviceName: {{.Values.redis.service}}
  replicas: {{.Values.redis.replicas}}
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: {{.Values.redis.deployment}}
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: {{.Values.redis.deployment}}
          image: redis:latest
          ports:
            - containerPort: {{.Values.redis.containerPort}}
              name: {{.Values.redis.deployment}}
          volumeMounts:
            - name: {{.Values.redis.storage}}
              mountPath: {{.Values.redis.mountPath}}
  volumeClaimTemplates:
    - metadata:
        name: {{.Values.redis.storage}}
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.redis.service}}
spec:
  type: ClusterIP
  selector:
    app: {{.Values.redis.deployment}}
  ports:
    - port: {{.Values.redis.servicePort}}
      targetPort: {{.Values.redis.containerPort}}
      name: {{.Values.redis.deployment}}
