apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.redis.pvc.name}}
spec:
  volumeName: {{.Values.redis.pv.name}}
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.redis.pvc.requestStorage}}
