apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
type: Opaque
data:
  POSTGRES_USERNAME: {{.Values.secret.POSTGRES_USER}}
  POSTGRES_PASSWORD: {{.Values.secret.POSTGRES_PASSWORD}}
  POSTGRES_DB: {{.Values.secret.POSTGRES_DB}}
  RABBITMQ_USERNAME: {{.Values.secret.RABBITMQ_DEFAULT_USER}}
  RABBITMQ_PASSWORD: {{.Values.secret.RABBITMQ_DEFAULT_PASS}}
