apiVersion: v1
kind: Secret
metadata:
  name: util-secret
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: {{.Values.secret.RABBITMQ_DEFAULT_USER}}
  RABBITMQ_DEFAULT_PASS: {{.Values.secret.RABBITMQ_DEFAULT_PASS}}
  POSTGRES_USER: {{.Values.secret.POSTGRES_USER}}
  POSTGRES_PASSWORD: {{.Values.secret.POSTGRES_PASSWORD}}
  POSTGRES_DB: {{.Values.secret.POSTGRES_DB}}
