apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  DATABASE_URL: "postgresql://awadhoot:awadhootk6@postgres:5432/jwt_security?schema=public"
