apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
  labels:
    app: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat-app
          image: awadhootk/rag-service:chat
          ports:
            - containerPort: 8081
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: chat-secret
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chat-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: chat-secret
                  key: POSTGRES_DB
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: chat-secret
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chat-secret
                  key: RABBITMQ_PASSWORD
            - name: SPRING_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: SPRING_REDIS_HOST
            - name: SPRING_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: SPRING_REDIS_PORT
            - name: INDEXING_HOST
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: INDEXING_HOST
            - name: INDEXING_PORT
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: INDEXING_PORT
            - name: RAG_HOST
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: RAG_HOST
            - name: RAG_PORT
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: RAG_PORT
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: RABBITMQ_PORT
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: POSTGRES_PORT

---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
