apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chromadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chromadb
  serviceName: "chromadb-service"
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: chromadb
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: chromadb-app
          image: awadhootk/rag-service:chromadb
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: chromadb-storage
              mountPath: /rag/chromadb
          env:
            - name: CHROMA_HOST
              valueFrom:
                configMapKeyRef:
                  name: chromadb-configmap
                  key: CHROMA_HOST
            - name: CHROMA_PORT
              valueFrom:
                configMapKeyRef:
                  name: chromadb-configmap
                  key: CHROMA_PORT
            - name: ANONYMIZED_TELEMETRY
              valueFrom:
                configMapKeyRef:
                  name: chromadb-configmap
                  key: ANONYMIZED_TELEMETRY
            - name: IS_PERSISTENT
              valueFrom:
                configMapKeyRef:
                  name: chromadb-configmap
                  key: IS_PERSISTENT
            - name: PERSIST_DIRECTORY
              valueFrom:
                configMapKeyRef:
                  name: chromadb-configmap
                  key: PERSIST_DIRECTORY
      volumes:
        - name: chromadb-storage
          persistentVolumeClaim:
            claimName: chromadb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: chromadb-service
spec:
  selector:
    app: chromadb
  ports:
    - protocol: TCP
      port: 8800
      targetPort: 8000
