apiVersion: v1
kind: Secret
metadata:
  name: indexing-secret
type: Opaque
data:
  GOOGLE_API_KEY: QUl6YVN5Qi1RdzQ0U2NPeU1iSXE5RXExNTFMYy15bFBBVDBMdVpN
  RABBITMQ_USERNAME: YWRtaW4=
  RABBITMQ_PASSWORD: cGFzc0AxMjM=
