apiVersion: v1
kind: ConfigMap
metadata:
  name: indexing-configmap
data:
  CHROMA_HOST: chromadb
  CHROMA_PORT: "8000"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
