apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag
  labels:
    app: rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag
  template:
    metadata:
      labels:
        app: rag
    spec:
      containers:
        - name: rag-app
          image: awadhootk/rag-service:rag
          ports:
            - containerPort: 8000
          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: rag-secret
                  key: GOOGLE_API_KEY
            - name: CHROMA_HOST
              valueFrom:
                configMapKeyRef:
                  name: rag-configmap
                  key: CHROMA_HOST
            - name: CHROMA_PORT
              valueFrom:
                configMapKeyRef:
                  name: rag-configmap
                  key: CHROMA_PORT
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: rag-configmap
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: rag-configmap
                  key: REDIS_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: rag-service
spec:
  selector:
    app: rag
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31000
