apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag
  labels:
    app: rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag
  template:
    metadata:
      labels:
        app: rag
    spec:
      containers:
        - name: rag
          image: awadhootk/rag-service:rag
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: rag-secret
                  key: GOOGLE_API_KEY
            - name: CHROMA_HOST
              valueFrom:
                configMapKeyRef:
                  name: rag-configmap
                  key: CHROMA_HOST
            - name: CHROMA_PORT
              valueFrom:
                configMapKeyRef:
                  name: rag-configmap
                  key: CHROMA_PORT
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: rag-configmap
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: rag-configmap
                  key: REDIS_PORT
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: rag-configmap
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: rag-configmap
                  key: RABBITMQ_PORT
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rag-secret
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rag-secret
                  key: RABBITMQ_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: rag-service
spec:
  selector:
    app: rag
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
