apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
type: Opaque
data:
  POSTGRES_USERNAME: YXdhZGhvb3Q=
  POSTGRES_PASSWORD: YXdhZGhvb3RrNg==
  POSTGRES_DB: and0X3NlY3VyaXR5
  RABBITMQ_USERNAME: YWRtaW4=
  RABBITMQ_PASSWORD: cGFzc0AxMjM=
