apiVersion: v1
kind: Secret
metadata:
  name: util-secret
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: YWRtaW4=
  RABBITMQ_DEFAULT_PASS: cGFzc0AxMjM=
  POSTGRES_USER: YXdhZGhvb3Q=
  POSTGRES_PASSWORD: YXdhZGhvb3RrNg==
  POSTGRES_DB: and0X3NlY3VyaXR5
